######################################################################
# Automatically generated by qmake (3.0) ?? 5? 9 18:50:53 2017
######################################################################

TEMPLATE = app
TARGET = IRdemo
INCLUDEPATH += .
QT += widgets
LIBS += -L. -lIr
# Input
HEADERS += cmdwidget.h irmainwindow.h palette.h playwidget.h
FORMS += cmdwidget.ui irmainwindow.ui
SOURCES += cmdwidget.cpp irmainwindow.cpp main.cpp playwidget.cpp
